name: minvest_forex_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.1
  firebase_messaging: ^15.0.2
  cloud_functions: ^5.0.2
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.0
  sign_in_with_apple: ^6.1.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  webview_flutter: ^4.8.0
  in_app_purchase: 3.1.13
  flutter_local_notifications: ^17.2.1
  device_info_plus: ^10.1.0
  crypto: ^3.0.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/