name: minvest_forex_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # --- Firebase Core Libraries (Synced Versions) ---
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  firebase_messaging: ^14.9.4
  cloud_functions: ^4.7.4

  # --- Authentication Providers ---
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.0
  sign_in_with_apple: ^6.1.1

  # --- Core Flutter/Dart Packages ---
  flutter_bloc: ^8.1.6
  equatable: ^2.0.6
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  intl: ^0.20.2

  # --- UI & Utility Packages ---
  cupertino_icons: ^1.0.2
  url_launcher: ^6.3.0
  image_picker: ^1.1.2

  # --- Platform Specific Packages ---
  webview_flutter: ^4.8.0
  in_app_purchase: ^3.2.0
  flutter_local_notifications: ^17.2.1
  device_info_plus: ^10.1.0
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/