name: minvest_forex_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.0.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  cupertino_icons: ^1.0.2
  image_picker: ^1.1.2
  firebase_storage: ^12.1.0
  sign_in_with_apple: ^6.1.1
  flutter_facebook_auth: ^7.0.0
  flutter_svg: ^2.0.9
  cloud_functions: ^5.0.1
  url_launcher: ^6.2.6
  webview_flutter: ^4.13.0
  in_app_purchase: ^3.2.0
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^17.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  intl: ^0.20.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/